name: TRaiCE SonarQube Code Scan
run-name: SonarQube Code Scan
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build
 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
          # SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SONAR_HOST_URL: https://sonarqube.traice.io/
          

      # Check the Quality Gate status.
      - name: SonarQube Quality Gate check
        id: sonarqube-quality-gate-check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time.
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN1 }}
      
      - name: "SonarQube Quality Gate Status"
        run: echo "The Quality Gate status is ${{ steps.sonarqube-quality-gate-check.outputs.quality-gate-status }}"
